### ISSUE TITLE
Save to local storage ?

### ISSUE THREAD

**Issue by johnoscott** [small-tech/jsdb#12]
For a browser-only use of JSDB, how can I use JSDB without a server and store to localstorage ?

and further to this, can I still use a server but implement a "local storage - first" solution that will allow offline use ?

**Comment by aral** [comment]
@johnoscott Unfortunately, there’s no way to do this currently. My use case for JSDB is currently server-side only. That said, if anyone comes up with creative ways of achieving this without introducing too much additional complexity, I’ll be happy to consider it.

PS. I’m in the process of moving the repository to Codeberg. If anyone wants to discuss implementing this there, please feel free to open an issue there.
