### ISSUE TITLE
Append-only means no row delete?

### ISSUE THREAD

**Issue by nielsbom** [small-tech/jsdb#7]
I like jsdb! So thanks :-)

I couldn't find in the docs or source how to delete a row in an array/table. Is that a feature or am I looking in the wrong place? I see [updating works](https://github.com/small-tech/jsdb/issues/5) but I'm not sure how to delete a row. 

I could resort to deleting the table and replacing it with the table-without-that-row but that seems brutish :-)

Thanks again!

**Comment by aral** [comment]
Hi there,

You’re welcome; happy you like it :)

To delete from an array, just use the regular array methods (`pop`, `splice`, etc.) Note that splicing can be slow (to see what it does, perform it and then `cat` your database table in terminal and see exactly how it works.

**Comment by nielsbom** [comment]
Ah that clears it up. Thanks!

**Comment by nielsbom** [comment]
I created a doc-PR, seems helpful.
https://github.com/small-tech/jsdb/pull/8

**Comment by aral** [comment]
Thank you, appreciate it. Will merge first chance I get :)
